### ISSUE TITLE
[Feat]: Support Overseas Version

### ISSUE THREAD

**Issue by prpjzz** [moesnow/March7thAssistant#13]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我确定这是一个从未被提出和实现过的功能。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 以及 [Pull Request](https://github.com/moesnow/March7thAssistant/pulls) 中找过我要提出的功能，没有找到相同功能的ISSUE和PR。
- [X] 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 需要添加的功能内容

Hello ~
Can you support the global version?

If possible, you can also add another language (English) to make it easier for us to use. I can help you with this, I guess.

**Comment by Eisaichen** [comment]
Global version alone should not be an issue, program itself seems doesn't care which version of the client you running.
However, you do need to change your game language settings to Chinese due to OCR stuff. what languages are supported actually depends on those 3rd-party projects, e.g. https://github.com/CHNZYX/Auto_Simulated_Universe response for the simulated universe. March7th itself is more like a launcher for those subsets.
